# **UnderSampling**

In [1]:
import numpy as np 
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/all_data.csv')

In [4]:
counts = df['Label'].value_counts().to_dict()

In [5]:
df.shape[0] , counts['BENIGN']

(2672997, 2117531)

In [6]:
attacks = df.shape[0] - counts['BENIGN']
nonattacks = counts['BENIGN']

In [7]:
attacks * 100 /(attacks+nonattacks)

20.780644347898633

In [8]:
'''
  if attacks no is 30% that means attacks = 30%
                                        x = 70%
                                          x = (7/3)*attacks
'''

'\n  if attacks no is 30% that means attacks = 30%\n                                        x = 70%\n                                          x = (7/3)*attacks\n'

In [9]:
requirednonattacks = (7/3)*attacks
requirednonattacks

1296087.3333333335

In [10]:
totaltoremove = round(nonattacks - requirednonattacks)
totaltoremove

821444

# **Removing Strategies ....**

In [11]:
arr = df.loc[df['Label'] == 'BENIGN']
att = df.loc[df['Label'] != 'BENIGN']
print(type(arr))

<class 'pandas.core.frame.DataFrame'>

In [12]:
# shuffling the benign df
df = arr.sample(frac=1).reset_index(drop=True)
df

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,206591,3653,443,2563,11945,6,388,3,2,0,...,20,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN
1,15810,1340,62379,1584,53,17,67,23902,1,1,...,32,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN
2,200623,2210,61860,2608,53,17,459,135,2,2,...,20,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN
3,39811,2209,50010,1956,443,6,479,44441,3,1,...,20,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN
4,37769,2144,62029,2549,53,17,10,8203573,2,2,...,32,982.0,0.00000,982.0,982.0,8120273.0,0.00000,8120273.0,8120273.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2117526,168951,1161,60406,1398,53,17,99,72083,1,1,...,20,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN
2117527,63830,2141,51448,397,443,6,311,118021669,16,14,...,20,83645.5,96587.25078,151943.0,15348.0,58900000.0,95081.82044,59000000.0,58900000.0,BENIGN
2117528,248043,2269,3101,8926,80,6,20759,2415424,6,4,...,20,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN
2117529,220067,2210,14987,411,80,6,463,418551,34,56,...,20,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN
2117530,85574,2263,60934,4409,80,6,21484,64049881,2,0,...,32,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,BENIGN

In [13]:
# Using drop() function to delete first n rows
df.drop(index=df.index[:totaltoremove],axis=0, inplace=True)
df.reset_index(inplace=True)
df.head(5)

,index,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,821444,35929,2100,443,2744,49916,6,14653,65,3,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,821445,195043,2210,52673,2608,53,17,160,91765,2,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,821446,58449,1337,45245,1593,53,17,27,295,2,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,821447,70012,696,58208,865,53,17,80,53034,4,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,821448,31918,2777,443,1590,50506,6,119,71,1,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [14]:
z = 50
'''
import random
## remove the non attacks rows at random
while True:
  print(type(df))
  if totaltoremove == 0 :
    break
  temp = z 
  if totaltoremove < z:
    temp = totaltoremove
  arr = []
  while True:
    if temp == 0:
      break
    x = random.randint(0,df.shape[0]-1)
    label = df.iloc[x]['Label'] 
    #label = df.get('Label', default="no_country")[x]
    if label == 'BENIGN' :
      #print(x,end=' ')
      arr.append(x)
      temp -= 1
  print('\n\n')
  arr = list(set(arr))
  print('dropped rows in dataframe', arr)
  print(df.shape[0])
  df = df.drop(arr)
  df.reset_index()
  totaltoremove -= len(arr)
  print('totalleft ',totaltoremove)
  print('size left',df.shape[0])
  #print(df.columns)
  '''
  ## this method takes lot of time... using efficient method in above cell

'\nimport random\n## remove the non attacks rows at random\nwhile True:\n  print(type(df))\n  if totaltoremove == 0 :\n    break\n  temp = z \n  if totaltoremove < z:\n    temp = totaltoremove\n  arr = []\n  while True:\n    if temp == 0:\n      break\n    x = random.randint(0,df.shape[0]-1)\n    label = df.iloc[x][\'Label\'] \n    #label = df.get(\'Label\', default="no_country")[x]\n    if label == \'BENIGN\' :\n      #print(x,end=\' \')\n      arr.append(x)\n      temp -= 1\n  print(\'\n\n\')\n  arr = list(set(arr))\n  print(\'dropped rows in dataframe\', arr)\n  print(df.shape[0])\n  df = df.drop(arr)\n  df.reset_index()\n  totaltoremove -= len(arr)\n  print(\'totalleft \',totaltoremove)\n  print(\'size left\',df.shape[0])\n  #print(df.columns)\n  '

**Concatenating the attack and non attack dataframe**

In [15]:
balanceddata = pd.concat([df,att])

# *Saving Back this Dataframe to csv :_)*

---

In [16]:
balanceddata.head(5)

,index,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,821444.0,35929,2100,443,2744,49916,6,14653,65,3,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,821445.0,195043,2210,52673,2608,53,17,160,91765,2,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,821446.0,58449,1337,45245,1593,53,17,27,295,2,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,821447.0,70012,696,58208,865,53,17,80,53034,4,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,821448.0,31918,2777,443,1590,50506,6,119,71,1,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [17]:
balanceddata.drop('index', inplace=True, axis=1)

In [18]:
balanceddata.head(5)

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,35929,2100,443,2744,49916,6,14653,65,3,1,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,195043,2210,52673,2608,53,17,160,91765,2,2,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,58449,1337,45245,1593,53,17,27,295,2,2,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,70012,696,58208,865,53,17,80,53034,4,2,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,31918,2777,443,1590,50506,6,119,71,1,1,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [19]:
balanceddata.columns.to_list()

['Flow ID',
 'Source IP',
 'Source Port',
 'Destination IP',
 'Destination Port',
 'Protocol',
 'Timestamp',
 'Flow Duration',
 'Total Fwd Packets',
 'Total Backward Packets',
 'Total Length of Fwd Packets',
 'Total Length of Bwd Packets',
 'Fwd Packet Length Max',
 'Fwd Packet Length Min',
 'Fwd Packet Length Mean',
 'Fwd Packet Length Std',
 'Bwd Packet Length Max',
 'Bwd Packet Length Min',
 'Bwd Packet Length Mean',
 'Bwd Packet Length Std',
 'Flow Bytes/s',
 'Flow Packets/s',
 'Flow IAT Mean',
 'Flow IAT Std',
 'Flow IAT Max',
 'Flow IAT Min',
 'Fwd IAT Total',
 'Fwd IAT Mean',
 'Fwd IAT Std',
 'Fwd IAT Max',
 'Fwd IAT Min',
 'Bwd IAT Total',
 'Bwd IAT Mean',
 'Bwd IAT Std',
 'Bwd IAT Max',
 'Bwd IAT Min',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'Fwd Header Length',
 'Bwd Header Length',
 'Fwd Packets/s',
 'Bwd Packets/s',
 'Min Packet Length',
 'Max Packet Length',
 'Packet Length Mean',
 'Packet Length Std',
 'Packet Length Variance',
 'FIN Flag Count',
 'SYN Flag Count',
 'RST Flag Count',
 'PSH Flag Count',
 'ACK Flag Count',
 'URG Flag Count',
 'CWE Flag Count',
 'ECE Flag Count',
 'Down/Up Ratio',
 'Average Packet Size',
 'Avg Fwd Segment Size',
 'Avg Bwd Segment Size',
 'Fwd Avg Bytes/Bulk',
 'Fwd Avg Packets/Bulk',
 'Fwd Avg Bulk Rate',
 'Bwd Avg Bytes/Bulk',
 'Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 'Subflow Fwd Bytes',
 'Subflow Bwd Packets',
 'Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 'Init_Win_bytes_backward',
 'act_data_pkt_fwd',
 'min_seg_size_forward',
 'Active Mean',
 'Active Std',
 'Active Max',
 'Active Min',
 'Idle Mean',
 'Idle Std',
 'Idle Max',
 'Idle Min',
 'Label']

In [20]:
balanceddata.to_csv('/content/drive/MyDrive/balanced_data.csv')

In [25]:
x = balanceddata.Label.value_counts().to_dict()

In [26]:
nonattacks = x['BENIGN']

In [27]:
attacks = balanceddata.shape[0] - nonattacks

In [28]:
attacks*100/balanceddata.shape[0]

30.000005400871594

In [29]:
nonattacks*100/balanceddata.shape[0]

69.99999459912841

# ***Finally 70 - 30 ratio acheived :-)***

In [30]:
##Done