In [1]:
# importing required libraries
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
FOLDER = '/content/drive/MyDrive/'
#FOLDER = 'C:\Users\Admin\Downloads\'

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
data = pd.read_csv(FOLDER + "balancedhalf_data.csv")

In [6]:
data.drop(data.columns[0] , inplace=True , axis=1)

# Removing Some layers for Unknown Label

In [7]:
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,110933,1546,64824,1902,32780,6,134,1,2,0,...,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,36715,2181,443,2746,39240,6,1741,64,1,1,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,60299,1538,10595,1901,53,17,113,310,2,2,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,81104,2143,63961,6800,443,6,394,287107,21,47,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,48640,1335,54985,1593,53,17,7,46854,2,2,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [8]:
data.Label.value_counts().to_dict()

{'BENIGN': 555466,
 'DoS Hulk': 231073,
 'PortScan': 158930,
 'DDoS': 128027,
 'DoS GoldenEye': 10293,
 'FTP-Patator': 7938,
 'SSH-Patator': 5897,
 'DoS slowloris': 5796,
 'DoS Slowhttptest': 5499,
 'Bot': 1966,
 'Infiltration': 36,
 'Heartbleed': 11}

In [9]:
5897+5796+5499+1966+36+11

19205

In [10]:
len(data)

1110932

In [11]:
1851553-19205

1832348

In [12]:
1920500/1851553 #percentage of data we will be using for threshold for unknown label :)

1.0372373893698965

In [13]:
toremove = ['SSH-Patator','DoS slowloris','DoS Slowhttptest','Bot','Infiltration','Heartbleed']
att = data.loc[(data['Label'].isin(toremove))]

In [14]:
att

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
555466,177144,1546,53966,2293,444,6,79,42664070,5,6,...,20,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,Infiltration
555467,177144,1546,53966,2293,444,6,79,2030,2,0,...,20,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,Infiltration
555468,177145,1546,54119,2293,444,6,88,119991834,5523,5525,...,20,997842.0,831471.3076,1585781.0,409903.0,8143987.5,1821773.648,9432176.0,6855799.0,Infiltration
555469,177146,1546,54122,2293,444,6,90,5005212,15,15,...,28,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,Infiltration
555470,177145,1546,54119,2293,444,6,90,119973135,4376,4374,...,20,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,Infiltration
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110927,9072,1495,46280,2560,22,6,249,13609590,22,32,...,32,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,SSH-Patator
1110928,9077,1495,46290,2560,22,6,249,13653780,22,33,...,32,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,SSH-Patator
1110929,9075,1495,46286,2560,22,6,249,13681270,22,33,...,32,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,SSH-Patator
1110930,9071,1495,46278,2560,22,6,249,13625617,22,33,...,32,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,SSH-Patator
1110931,9074,1495,46284,2560,22,6,249,13652185,22,33,...,32,0.0,0.0000,0.0,0.0,0.0,0.000,0.0,0.0,SSH-Patator

In [15]:
att.Label.unique()

array(['Infiltration', 'DoS slowloris', 'DoS Slowhttptest', 'Heartbleed',
       'Bot', 'SSH-Patator'], dtype=object)

In [16]:
data.drop(att.index,axis=0 , inplace=True, errors='ignore')

In [17]:
data.Label.unique()

array(['BENIGN', 'DDoS', 'DoS Hulk', 'DoS GoldenEye', 'PortScan',
       'FTP-Patator'], dtype=object)

In [18]:
data.shape

(1091727, 84)

## Normalization On Data
# **Data Normalization**

In [19]:
# importing required libraries for normalizing data
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

In [20]:
# selecting numeric attributes columns from data
numeric_col = data.select_dtypes(include='number').columns

In [21]:
# using standard scaler for normalizing
std_scaler = MinMaxScaler()
def normalization(df,col):
  for i in col:
    arr = df[i]
    arr = np.array(arr)
    df[i] = std_scaler.fit_transform(arr.reshape(len(arr),1))
  return df
# calling the normalization() function
data = normalization(data.copy(),numeric_col)

In [22]:
# data after normalization
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0.445135,0.187690,0.989151,0.196143,0.500191,0.352941,0.005155,1.083333e-07,0.000005,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,0.147324,0.264781,0.006760,0.283180,0.598764,0.352941,0.066974,6.333333e-07,0.000000,0.000003,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,0.241959,0.186718,0.161669,0.196040,0.000809,1.000000,0.004347,2.683333e-06,0.000005,0.000007,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,0.325442,0.260168,0.975982,0.701248,0.006760,0.352941,0.015157,2.392658e-03,0.000092,0.000162,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,0.195175,0.162074,0.839017,0.164278,0.000809,1.000000,0.000269,3.905500e-04,0.000005,0.000007,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

# **One-hot-encoding**

In [23]:
# selecting numeric attributes columns from data
non_numeric_col = data.select_dtypes(exclude='number').columns

In [24]:
# creating a dataframe with only categorical attributes
categorical = data[non_numeric_col]
categorical.head()

    Label
0  BENIGN
1  BENIGN
2  BENIGN
3  BENIGN
4  BENIGN

In [25]:
# one-hot-encoding categorical attributes using pandas.get_dummies() function
categorical = pd.get_dummies(categorical,columns=non_numeric_col)
categorical.head()

,Label_BENIGN,Label_DDoS,Label_DoS GoldenEye,Label_DoS Hulk,Label_FTP-Patator,Label_PortScan
0,1,0,0,0,0,0
1,1,0,0,0,0,0
2,1,0,0,0,0,0
3,1,0,0,0,0,0
4,1,0,0,0,0,0

In [26]:
X = data.drop('Label' , axis=1)

In [27]:
X.head(1)

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,0.445135,0.18769,0.989151,0.196143,0.500191,0.352941,0.005155,1.083333e-07,0.000005,0.0,...,0.000005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
y = categorical

In [29]:
y.head(1)

,Label_BENIGN,Label_DDoS,Label_DoS GoldenEye,Label_DoS Hulk,Label_FTP-Patator,Label_PortScan
0,1,0,0,0,0,0

https://glassboxmedicine.com/2019/05/26/classification-sigmoid-vs-softmax/#:~:text=The%20probabilities%20produced%20by%20a%20softmax%20will%20always%20sum%20to,decrease%20by%20an%20equivalent%20amount.

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#  Convolutional Neural Networks

In [31]:
X_train.shape , y_train.shape , X_test.shape

((731457, 83), (731457, 6), (360270, 83))

In [32]:
X_train = X_train.to_numpy().reshape(-1, 83,1)
X_test = X_test.to_numpy().reshape(-1, 83,1)

## Model Training

In [33]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense,Dropout,LSTM,Embedding,SimpleRNN, GRU,Activation,Flatten
from tensorflow.keras.layers import Conv1D,MaxPool1D, Flatten
from tensorflow.keras.utils import plot_model
from tensorflow.keras.preprocessing import sequence
from sklearn.metrics import (precision_score, recall_score,confusion_matrix,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
import pandas as pd
from tensorflow.keras import callbacks
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
import matplotlib.pyplot as plt

In [34]:
model_cnn = Sequential()
model_cnn.add(Conv1D(64, 3, padding="same",activation="relu",input_shape=(83, 1)))
model_cnn.add(Conv1D(64, 3, padding="same", activation="relu"))
model_cnn.add(MaxPool1D(pool_size=(2)))
model_cnn.add(Conv1D(128, 3, padding="same", activation="relu"))
model_cnn.add(Conv1D(128, 3, padding="same", activation="relu"))
model_cnn.add(MaxPool1D(pool_size=(2)))
model_cnn.add(Flatten())
model_cnn.add(Dense(128, activation="relu"))
model_cnn.add(Dropout(0.5))
model_cnn.add(Dense(6, activation="softmax"))

In [35]:
model_cnn.compile(loss="binary_crossentropy", optimizer="adam",metrics=['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stoppoing

#FIT AND SAVE MODEL FOR FUTURE
model_cnn.fit(X_train, y_train, epochs=1000,validation_data=(X_test, y_test),callbacks=[es])
model_cnn.save(FOLDER+"model_split_softmax_cnn_model.hdf5")

Epoch 1/1000
22859/22859 [==============================] - 191s 8ms/step - loss: 0.0067 - accuracy: 0.9943 - val_loss: 9.0885e-04 - val_accuracy: 0.9992
Epoch 2/1000
22859/22859 [==============================] - 185s 8ms/step - loss: 0.0013 - accuracy: 0.9992 - val_loss: 0.0014 - val_accuracy: 0.9994
Epoch 3/1000
22859/22859 [==============================] - 184s 8ms/step - loss: 0.0010 - accuracy: 0.9994 - val_loss: 7.7035e-04 - val_accuracy: 0.9995
Epoch 4/1000
22859/22859 [==============================] - 172s 8ms/step - loss: 9.0095e-04 - accuracy: 0.9995 - val_loss: 0.0038 - val_accuracy: 0.9987
Epoch 5/1000
22859/22859 [==============================] - 174s 8ms/step - loss: 9.1530e-04 - accuracy: 0.9995 - val_loss: 0.0014 - val_accuracy: 0.9993
Epoch 6/1000
22859/22859 [==============================] - 174s 8ms/step - loss: 8.6851e-04 - accuracy: 0.9996 - val_loss: 4.4167e-04 - val_accuracy: 0.9997
Epoch 7/1000
22859/22859 [==============================] - 183s 8ms/step - loss: 9.0005e-04 - accuracy: 0.9995 - val_loss: 4.6292e-04 - val_accuracy: 0.9998
Epoch 8/1000
22859/22859 [==============================] - 183s 8ms/step - loss: 8.1959e-04 - accuracy: 0.9996 - val_loss: 5.8972e-04 - val_accuracy: 0.9997
Epoch 9/1000
22859/22859 [==============================] - 173s 8ms/step - loss: 9.5726e-04 - accuracy: 0.9995 - val_loss: 0.0011 - val_accuracy: 0.9997
Epoch 10/1000
22859/22859 [==============================] - 183s 8ms/step - loss: 9.4445e-04 - accuracy: 0.9995 - val_loss: 3.9394e-04 - val_accuracy: 0.9998
Epoch 11/1000
22859/22859 [==============================] - 172s 8ms/step - loss: 9.5043e-04 - accuracy: 0.9996 - val_loss: 6.2960e-04 - val_accuracy: 0.9999
Epoch 12/1000
22859/22859 [==============================] - 171s 7ms/step - loss: 0.0010 - accuracy: 0.9995 - val_loss: 0.0011 - val_accuracy: 0.9994